version: "3.3"

services:
  sns-mysql:
    image: "mysql:8.0"
    container_name: sns-mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: sns-db
      MYSQL_ROOT_PASSWORD: 1234
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
