spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:33061/sns-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    group:
      dev: "dev"

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    logging.level:
      org.hibernate.SQL: debug
    properties:
      hibernate:
        show_sql: true
